###
DELETE  http://localhost:4004/CatalogService/Employees/25

//http://151c23dbtrial-dev-emrej-srv.cfapps.us10-001.hana.ondemand.com/CatalogService/Employees/5

###
POST http://localhost:4004/CatalogService/Employees
Content-Type: application/json


  {
   
  "fname": "Muzammil",
  "lname": "Ansari",
  "desig": "Technical Associate",
  "email": "muzammil.ansari@aarini.com",
  "skills": "Capm.ui5,html",
  "country_ID": 1,
  "State": "MH",
  "city": "Pune",
  "doj": "2023-03-06",
  "yoe": 1,
  "gender": "Male",
  "department_ID": null,
  "projects_ID": null,
  "leave": false,
  "reportingPerson": "Harish",
  "Phno": null
}
